### ISSUE TITLE
Invalid left-hand side in assignment with var

### ISSUE THREAD

**Issue by vjau** [mologie/meteor-typescript#4]
Hi,
i have a strange bug (i guess) with your package.
I have some external javascript code which i define in a d.ts file like this:

``` js
declare class LocalCollectionsPersister{
    constructor();
    createCollection(name: string):Mongo.Collection<any>;
    getCollections():{[name:string]:Mongo.Collection<any>};
}
```

I include the d.ts file in my ts source file and then i do :

``` js
var lcp = new LocalCollectionsPersister();
```

But build time is interrupted with the compiler complaining that 
    "Invalid left-hand side in assignment with var"

I have read and re-read and re-re-read and i cannot figure what's wrong my code.

At last, i have tried to compile it by hand with tsc 1.5 beta and with tsc 1.4.1 included in your package. Both succeed silently so i guess it must be a problem with your package.

What's stranger is that if i replace var with let, compilation succeed....

Thank you for your help.

**Comment by vjau** [comment]
Ok, it works, thanks !

**Comment by mologie** [comment]
Woops, now this is a ticket I have not seen for quite some time, I am surprised I have not commented in here yet. Obligatory sorry for the delay with the initial fix, and thank you for confirming that this is fixed. Cheers, Oliver
