### ISSUE TITLE
TypeScript 1.5 support

### ISSUE THREAD

**Issue by mologie** [mologie/meteor-typescript#5]
TypeScript 1.5 is now stable - this plugin's bundled TypeScript compiler should be updated to TS 1.5.

Notes to self:
- TS's compiler API is still not stable - changes that I have spotted so far are marked in the source code
- TS introduces a new compile server process which I might use in order to remove the ugly Meteor build system integration/workaround

**Comment by Schonhoffer** [comment]
+1!

**Comment by vjau** [comment]
Do you know that Meteor introduces a completely new compiler/plugin api in 1.2 ?
https://forums.meteor.com/t/try-out-a-preview-of-batch-build-plugins-and-other-1-2-features/7374/18
With both changes in TS compiler API and changes in Meteor compiler API, i fear your plugin would have to be completely rewritten. I tried a quick 'n dirty hacking of your plugin to make it work with 1.5, but it seemed to me a rewrite from scratch would be easier :( Hope i'm wrong on this one.

**Comment by mologie** [comment]
The old TypeScript compiler API is still there - the new API (the TypeScript compile server) is built on top of it; my plugin should continue to work with TS 1.5 with minor changes on Meteor 1.1.

I have not looked into the new Meteor 1.2 build API yet, but figure that major changes are required.

**Comment by samuba** [comment]
+1

**Comment by mologie** [comment]
TypeScript 1.8.9 is now supported on Meteor 1.2 (use v1.0.0-rc.1 tag) and 1.3-rc.8 (use the v.1.1.0-rc.1 tag).
